build: off

clone_folder: c:\gopath\src\go-hep.org\x\hep

branches:
  only:
    - master

environment:
  GOPATH: c:\gopath
  PATH: '%GOPATH%\bin;%PATH%'

stack: go 1.10

build_script:
  - go get -v -t -tags purego ./...

test_script:
  - go test -tags purego ./...
